<a href="https://colab.research.google.com/github/farhadahmed1/pytorch/blob/main/pytorch1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:

import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

1.13.0+cu116


In [ ]:
#Introduction to Tensor

##creat in tensor
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
# Get tensor back as Python int
scalar.item()

7

In [ ]:
scalar.ndim

0

In [ ]:
# Vector
vector= torch.tensor([7,3])
vector

tensor([7, 3])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
# Matrix
matrix = torch.tensor([[7,8],
                      [9,10]])
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
matrix.ndim
 

2

In [ ]:
matrix[1]

tensor([ 9, 10])

In [ ]:
matrix.shape

torch.Size([2, 2])

In [ ]:
# Tensor
Tensor = torch.tensor([[[1,3,4],
                       [2,4,6],
                       [7,9,10],[29,67,898]]])
Tensor

tensor([[[  1,   3,   4],
         [  2,   4,   6],
         [  7,   9,  10],
         [ 29,  67, 898]]])

In [ ]:
Tensor.shape

torch.Size([1, 4, 3])